/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/about': RouteRecordInfo<'/about', '/about', Record<never, never>, Record<never, never>>,
    '/posts/AppleCinemaDisplay 1999/': RouteRecordInfo<'/posts/AppleCinemaDisplay 1999/', '/posts/AppleCinemaDisplay 1999', Record<never, never>, Record<never, never>>,
    '/posts/iBook 1999/': RouteRecordInfo<'/posts/iBook 1999/', '/posts/iBook 1999', Record<never, never>, Record<never, never>>,
    '/posts/iMac 1998/': RouteRecordInfo<'/posts/iMac 1998/', '/posts/iMac 1998', Record<never, never>, Record<never, never>>,
    '/posts/iMac 1999/': RouteRecordInfo<'/posts/iMac 1999/', '/posts/iMac 1999', Record<never, never>, Record<never, never>>,
    '/posts/iMac 2003/': RouteRecordInfo<'/posts/iMac 2003/', '/posts/iMac 2003', Record<never, never>, Record<never, never>>,
    '/posts/iMac 2004/': RouteRecordInfo<'/posts/iMac 2004/', '/posts/iMac 2004', Record<never, never>, Record<never, never>>,
    '/posts/iMac 2005/': RouteRecordInfo<'/posts/iMac 2005/', '/posts/iMac 2005', Record<never, never>, Record<never, never>>,
    '/posts/iMac 2007/': RouteRecordInfo<'/posts/iMac 2007/', '/posts/iMac 2007', Record<never, never>, Record<never, never>>,
    '/posts/iPad 2010/': RouteRecordInfo<'/posts/iPad 2010/', '/posts/iPad 2010', Record<never, never>, Record<never, never>>,
    '/posts/iPhone 2007/': RouteRecordInfo<'/posts/iPhone 2007/', '/posts/iPhone 2007', Record<never, never>, Record<never, never>>,
    '/posts/iPhone4 2010/': RouteRecordInfo<'/posts/iPhone4 2010/', '/posts/iPhone4 2010', Record<never, never>, Record<never, never>>,
    '/posts/iPhone5C 2013/': RouteRecordInfo<'/posts/iPhone5C 2013/', '/posts/iPhone5C 2013', Record<never, never>, Record<never, never>>,
    '/posts/iPhoneX 2017/': RouteRecordInfo<'/posts/iPhoneX 2017/', '/posts/iPhoneX 2017', Record<never, never>, Record<never, never>>,
    '/posts/MacBookAir 2008/': RouteRecordInfo<'/posts/MacBookAir 2008/', '/posts/MacBookAir 2008', Record<never, never>, Record<never, never>>,
    '/posts/MacBookPro 2008/': RouteRecordInfo<'/posts/MacBookPro 2008/', '/posts/MacBookPro 2008', Record<never, never>, Record<never, never>>,
    '/posts/MacOSX 1999/': RouteRecordInfo<'/posts/MacOSX 1999/', '/posts/MacOSX 1999', Record<never, never>, Record<never, never>>,
    '/posts/PowerMacG3 1999/': RouteRecordInfo<'/posts/PowerMacG3 1999/', '/posts/PowerMacG3 1999', Record<never, never>, Record<never, never>>,
    '/posts/PowerMacG4 1999/': RouteRecordInfo<'/posts/PowerMacG4 1999/', '/posts/PowerMacG4 1999', Record<never, never>, Record<never, never>>,
    '/posts/PowerMacG4Cube 1999/': RouteRecordInfo<'/posts/PowerMacG4Cube 1999/', '/posts/PowerMacG4Cube 1999', Record<never, never>, Record<never, never>>,
  }
}
